#include <spn/dcp.h>
#include <spn/errno.h>

#define BLOCK_TYPE(option, sub_option) ((option) << 8 | (sub_option))

uint32_t dcp_option_bitmap(uint8_t option, uint8_t sub_option)
{
    switch (BLOCK_TYPE(option, sub_option)) {
    case BLOCK_TYPE(DCP_OPTION_IP, DCP_SUB_OPT_IP_MAC):
        return DCP_BITMAP_IP_MAC_ADDRESS;
    case BLOCK_TYPE(DCP_OPTION_IP, DCP_SUB_OPT_IP_PARAM):
        return DCP_BITMAP_IP_PARAMETER;
    case BLOCK_TYPE(DCP_OPTION_IP, DCP_SUB_OPT_IP_FULL_SUITE):
        return DCP_BITMAP_IP_FULL_IP_SUITE;
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_NAME_OF_VENDOR):
        return DCP_BITMAP_DEVICE_PROPERTIES_NAME_OF_VENDOR;
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_NAME_OF_STATION):
        return DCP_BITMAP_DEVICE_PROPERTIES_NAME_OF_STATION;
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_DEVICE_ID):
        return DCP_BITMAP_DEVICE_PROPERTIES_DEVICE_ID;
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_DEVICE_ROLE):
        return DCP_BITMAP_DEVICE_PROPERTIES_DEVICE_ROLE;
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_DEVICE_OPTIONS):
        return DCP_BITMAP_DEVICE_PROPERTIES_DEVICE_OPTIONS;
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_NAME_OF_ALIAS):
        return DCP_BITMAP_DEVICE_PROPERTIES_NAME_OF_ALIAS;
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_DEVICE_INSTANCE):
        return DCP_BITMAP_DEVICE_PROPERTIES_DEVICE_INSTANCE;
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_OEM_DEVICE_ID):
        return DCP_BITMAP_DEVICE_PROPERTIES_OEM_DEVICE_ID;
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_STD_GATEWAY):
        return DCP_BITMAP_DEVICE_PROPERTIES_STANDARD_GATEWAY;
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_RSI):
        return DCP_BITMAP_DEVICE_PROPERTIES_RSI_PROPERTIES;
    case BLOCK_TYPE(DCP_OPTION_DHCP, DCP_SUB_OPT_DHCP_UNKNOW):
        return DCP_BITMAP_DHCP_DHCP;
    case BLOCK_TYPE(DCP_OPTION_CONTROL, DCP_SUB_OPT_CTRL_START):
        return DCP_BITMAP_CONTROL_START;
    case BLOCK_TYPE(DCP_OPTION_CONTROL, DCP_SUB_OPT_CTRL_STOP):
        return DCP_BITMAP_CONTROL_STOP;
    case BLOCK_TYPE(DCP_OPTION_CONTROL, DCP_SUB_OPT_CTRL_SIGNAL):
        return DCP_BITMAP_CONTROL_SIGNAL;
    case BLOCK_TYPE(DCP_OPTION_CONTROL, DCP_SUB_OPT_CTRL_RESPONSE):
        return DCP_BITMAP_CONTROL_RESPONSE;
    case BLOCK_TYPE(DCP_OPTION_CONTROL, DCP_SUB_OPT_CTRL_FACTORY_RESET):
        return DCP_BITMAP_CONTROL_FACTORY_RESET;
    case BLOCK_TYPE(DCP_OPTION_CONTROL, DCP_SUB_OPT_CTRL_RESET_TO_FACTORY):
        return DCP_BITMAP_CONTROL_RESET_TO_FACTORY;
    case BLOCK_TYPE(DCP_OPTION_DEV_INITIATIVE, DCP_SUB_OPT_DEV_INITIATIVE):
        return DCP_BITMAP_DEVICE_INITIATIVE_DEVICE_INITIATIVE;
    case BLOCK_TYPE(DCP_OPTION_NME_DOMAIN, DCP_SUB_OPT_NME_DOMAIN):
        return DCP_BITMAP_NME_DOMAIN_NME_DOMAIN;
    case BLOCK_TYPE(DCP_OPTION_NME_DOMAIN, DCP_SUB_OPT_NME_PRIORITY):
        return DCP_BITMAP_NME_DOMAIN_NME_PRIO;
    case BLOCK_TYPE(DCP_OPTION_NME_DOMAIN, DCP_SUB_OPT_NME_PARAM_UUID):
        return DCP_BITMAP_NME_DOMAIN_NME_PARAMETER_UUID;
    case BLOCK_TYPE(DCP_OPTION_NME_DOMAIN, DCP_SUB_OPT_NME_NAME):
        return DCP_BITMAP_NME_DOMAIN_NME_NAME;
    case BLOCK_TYPE(DCP_OPTION_NME_DOMAIN, DCP_SUB_OPT_NME_CIM_INTERFACE):
        return DCP_BITMAP_NME_DOMAIN_CIM_INTERFACE;
    case BLOCK_TYPE(DCP_OPTION_ALL_SELECTOR, DCP_SUB_OPT_ALL_SELECTOR):
        return DCP_BITMAP_ALL_SELECTOR;
    default:
        return 0;
    }
}
