#include <spn/config.h>
#include <spn/dcp.h>
#include <spn/sys.h>

#define BLOCK_TYPE(opt, sub_opt) ((opt) << 8 | (sub_opt))

#if SPN_DEBUG
const char* dcp_option_name(uint8_t option, uint8_t sub_option) {
  switch (BLOCK_TYPE(option, sub_option)) {
    case BLOCK_TYPE(DCP_OPTION_IP, DCP_SUB_OPT_IP_MAC):
      return "IP_MAC";
    case BLOCK_TYPE(DCP_OPTION_IP, DCP_SUB_OPT_IP_PARAM):
      return "IP_PARAM";
    case BLOCK_TYPE(DCP_OPTION_IP, DCP_SUB_OPT_IP_FULL_SUITE):
      return "IP_FULL_SUITE";
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_NAME_OF_VENDOR):
      return "DEV_PROP_NAME_OF_VENDOR";
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_NAME_OF_STATION):
      return "DEV_PROP_NAME_OF_STATION";
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_DEVICE_ID):
      return "DEV_PROP_DEVICE_ID";
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_DEVICE_ROLE):
      return "DEV_PROP_DEVICE_ROLE";
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_DEVICE_OPTIONS):
      return "DEV_PROP_DEVICE_OPTIONS";
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_NAME_OF_ALIAS):
      return "DEV_PROP_NAME_OF_ALIAS";
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_DEVICE_INSTANCE):
      return "DEV_PROP_DEVICE_INSTANCE";
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_OEM_DEVICE_ID):
      return "DEV_PROP_OEM_DEVICE_ID";
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_STD_GATEWAY):
      return "DEV_PROP_STD_GATEWAY";
    case BLOCK_TYPE(DCP_OPTION_DEV_PROP, DCP_SUB_OPT_DEV_PROP_RSI):
      return "DEV_PROP_RSI";
    case BLOCK_TYPE(DCP_OPTION_DHCP, DCP_SUB_OPT_DHCP_CLIENT_IDENT):
      return "DHCP_CLIENT_IDENT";
    case BLOCK_TYPE(DCP_OPTION_CONTROL, DCP_SUB_OPT_CTRL_START):
      return "CTRL_START";
    case BLOCK_TYPE(DCP_OPTION_CONTROL, DCP_SUB_OPT_CTRL_STOP):
      return "CTRL_STOP";
    case BLOCK_TYPE(DCP_OPTION_CONTROL, DCP_SUB_OPT_CTRL_SIGNAL):
      return "CTRL_SIGNAL";
    case BLOCK_TYPE(DCP_OPTION_CONTROL, DCP_SUB_OPT_CTRL_RESPONSE):
      return "CTRL_RESPONSE";
    case BLOCK_TYPE(DCP_OPTION_CONTROL, DCP_SUB_OPT_CTRL_FACTORY_RESET):
      return "CTRL_FACTORY_RESET";
    case BLOCK_TYPE(DCP_OPTION_CONTROL, DCP_SUB_OPT_CTRL_RESET_TO_FACTORY):
      return "CTRL_RESET_TO_FACTORY";
    case BLOCK_TYPE(DCP_OPTION_DEV_INITIATIVE, DCP_SUB_OPT_DEV_INITIATIVE):
      return "DEV_INITIATIVE";
    case BLOCK_TYPE(DCP_OPTION_NME_DOMAIN, DCP_SUB_OPT_NME_DOMAIN):
      return "NME_DOMAIN";
    case BLOCK_TYPE(DCP_OPTION_NME_DOMAIN, DCP_SUB_OPT_NME_PRIORITY):
      return "NME_PRIORITY";
    case BLOCK_TYPE(DCP_OPTION_NME_DOMAIN, DCP_SUB_OPT_NME_PARAM_UUID):
      return "NME_PARAM_UUID";
    case BLOCK_TYPE(DCP_OPTION_NME_DOMAIN, DCP_SUB_OPT_NME_NAME):
      return "NME_NAME";
    case BLOCK_TYPE(DCP_OPTION_NME_DOMAIN, DCP_SUB_OPT_NME_CIM_INTERFACE):
      return "NME_CIM_INTERFACE";
    case BLOCK_TYPE(DCP_OPTION_ALL_SELECTOR, DCP_SUB_OPT_ALL_SELECTOR):
      return "ALL_SELECTOR";
    default:
      return "UNKNOWN";
  }
}
#else
const char* dcp_option_name(uint8_t option, uint8_t sub_option) {
  SPN_UNUSED_ARG(option);
  SPN_UNUSED_ARG(sub_option);
  return "unknown(should enable SPN_DEBUG)";
}
#endif
