name: Daily Unit Tests

on:
  schedule: 
    - cron: '0 5,17 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: packages setup
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: valgrind
          
      - name: Setup Ninja
        uses: turtlesec-no/get-ninja@1.1.0
        
      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1

      - name: Setup Lcov
        uses: hrishikesh-kadam/setup-lcov@v1.0.0

      - name: Set up CMake
        uses: lukka/run-cmake@v10.7
        with:
          cmake-version: '3.21'
          configurePreset: 'Test'

      - name: Build and run tests
        run: |
          cmake --preset Test
          cmake --build build/tests --target tests
          ./build/tests/tests
      
      - name: Generate coverage report
        run: |
          cmake --build build/tests --target tests_cov

      - name: Report coverage
        run: |
          lcov -l build/tests/coverage.info
          lcov --summary build/tests/coverage.info
          
      - name: Generate a coverage value
        id: coverage
        run: |
          COVERAGE="$( lcov --summary build/tests/coverage.info | grep lines | awk '{print $2}' )"
          echo "##[set-output name=lines;]${COVERAGE}"
          
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 1c0c78e94fa6dd8c805b2bca05541c8a
          filename: spn.json
          label: Line
          message: ${{ steps.coverage.outputs.lines }}
          color: blue

      - name: Memory leak check
        run: |
          valgrind --leak-check=full ./build/tests/tests
          
