name: Daily Unit Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: packages setup
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: valgrind
          
      - name: Setup Ninja
        uses: turtlesec-no/get-ninja@1.1.0
        
      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1

      - name: Setup Lcov
        uses: hrishikesh-kadam/setup-lcov@v1.0.0

      - name: Set up CMake
        uses: lukka/run-cmake@v10.7
        with:
          cmake-version: '3.21'
          configurePreset: 'Test'

      - name: Build and run tests
        run: |
          cmake --preset Test
          cmake --build build/tests --target tests
          ./build/tests/tests
      
      - name: Generate coverage report
        run: |
          cmake --build build/tests --target tests_cov
          
      - name: Upload coverage report
        uses: zgosalvez/github-actions-report-lcov@v4.1.12
        with:
          coverage-files: build/tests/coverage.info
          minimum-coverage: 80
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: apps/my-first-app
          update-comment: true
      
      - name: Memory leak check
        run: |
          valgrind --leak-check=full ./build/tests/tests
          
